# Dockerfile for React client

FROM node:18-alpine AS build-stage

WORKDIR /app

# copy local files to app folder
COPY ./package*.json /app/
COPY ./postcss.config.js /app/
COPY ./tailwind.config.js /app/
COPY ./src/ /app/src/
COPY ./public/ /app/public/
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Installing dependencies, you'll most likely see warnings, you can ignore
# most of these.
RUN npm i
RUN npm run build

FROM nginx:1.24.0-alpine as production-stage

COPY --from=build-stage /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
